### ISSUE TITLE
Stolen eth?

### ISSUE THREAD

**Issue by jawnpeezy** [alchemistcoin/alchemist#6]
I followed all the steps in the tutorial and sent eth to my generated address, (this was over 12 hrs ago) and it still is not showing up. Whats the problem?

**Comment by zenflow** [comment]
> I followed all the steps in the tutorial and sent eth to my generated address, (this was over 12 hrs ago) and it still is not showing up. Whats the problem?

/cc @thegostep

**Comment by thegostep** [comment]
Best to ask for help on the discord

discord.alchemist.wtf
